language: cpp
sudo: true
os: "linux"
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update && sudo apt-get dist-upgrade
install:
  - sudo apt-get install libsfml-dev

script:
  - make
#  - ./main
